export enum DomainExceptionCode {
	DEFAULT_DOMAIN_EXCEPTION = 'DEFAULT_DOMAIN_EXCEPTION',
	USER_NAME_REQUIERED = 'USER_NAME_REQUIERED',
	USER_LASTNAME_REQUIERED = 'USER_LASTNAME_REQUIERED',
	USER_EMAIL_REQUIERED = 'USER_EMAIL_REQUIERED',
	USER_EMAIL_INVALID = 'USER_EMAIL_INVALID',
	USER_PASSWORD_REQUIERED = 'USER_PASSWORD_REQUIERED',
	USER_PASSWORD_LENGHT_INVALID = 'USER_PASSWORD_LENGHT_INVALID',
	USER_GUID_INVALID = 'USER_GUID_INVALID',
	USER_NOT_FOUND = 'USER_NOT_FOUND',
}